### ISSUE TITLE
Rotation of the blocks

### ISSUE THREAD

**Issue by MNUEL174** [MarvinD00/LearningAgent#2]
Question is if the rotation of the blocks should be calculated on the block themselves or if we create seperate rotated blocks.

**Comment by MarvinD00** [comment]
kinda done with this a few unexpected behaviour bugs but for now it shall be good

**Comment by MarvinD00** [comment]
this is the only thing thats bugging me right now (will work on this next)
you can force the game to softlock because the game does not prevent invalid rotations in certain cases.
This can break the game pretty easily and has to be fixed (nothing else is left anyway)
After this i think the game is pretty much done and playable everything else would be cosmetic or nice to have but
we should probably start working on the agent at that point

**Comment by MarvinD00** [comment]
done
